version: 2
jobs:
  build:
    working_directory: ~/circleci-maidchan
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            mkdir -p "${CIRCLE_WORKING_DIRECTORY}/results/junit/"
            pytest --junitxml="results/junit/results-${CIRCLE_NODE_INDEX}.xml" --verbose --cov=maidchan --cov-report term-missing tests
      - store_artifacts:
          path: "results"
